name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH
        run: sudo apt-get install -y ssh

      - name: Deploy code
        run: |
          ssh -i ${{ secrets.PEM_PASS }} ec2-user@ec2-18-117-241-206.us-east-2.compute.amazonaws.com cd contactlessWhatsapp && git pull origin main
