name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

jobs:
  deploy:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH
        run: sudo apt-get install -y ssh

      - name: Deploy code
        run: |
          ssh -i /Users/galvarez/Projects/contactless-whatsapp.pem ec2-user@ec2-18-117-241-206.us-east-2.compute.amazonaws.com "cd contactlessWhatsapp && git pull origin main"
